id: I87D6A546
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T12:19:30+00:00'
last_modified: '2022-06-08T13:04:57.513318+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16816
  title: 'བོན་ཆོས་རྣམ་འབྱེད་སྣང་གསལ་རིག་པའི་མེ་མོང་། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7D9B:
      image_group_id: I8LS16824
      title: ''
      total_pages: 100
      order: 1
      base_file: 7D9B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
